services:
  - type: web
    name: rh-turnover-api
    runtime: docker
    region: frankfurt
    plan: free
    branch: main
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
